### PR TITLE
Bump and rename `ddtrace` -> `datadog`

### PR DESCRIPTION
**Pull request by artrybalko**
Datadog updated the name of the tracing gem in version 2 from `ddtrace` to `datadog`

## Types of Changes

- Maintenance.

## Contribution

- [ ] I added tests for my changes.
- [ ] I tested my changes locally.
- [ ] I agree to the [Developer's Certificate of Origin 1.1](https://developercertificate.org/).

### CODE REVIEW

**Comment by artrybalko** [comment]
@ioquatix thanks for updating the gem to support DD v2!

**Comment by ioquatix** [comment]
No problem, thanks for making a PR, it was helpful. Unfortunately, a few more changes were required!

What are you using this gem for?

**Comment by artrybalko** [comment]
We switched one of our Rails applications that makes a ton of external API calls to `falcon` and `async-http-faraday` a few months ago at IFTTT and used this gem for our Datadog monitoring. Had to take it out recently as it was blocking the datadog gem upgrade. I'm putting it back now.

**Comment by ioquatix** [comment]
Nice, how is it working out?

**Comment by artrybalko** [comment]
Really quite well. We were able to shift some workloads to the app in question that were previously handled by a JVM app that the old Rails+Unicorn architecture just couldn't accommodate when given comparable compute resources. No need for nginx in from of it either.
We are now experimenting with `async-http` and Async in a couple other places

**Comment by ioquatix** [comment]
I'm exploring ways to sustain the development of Falcon. Are there things as a business that you'd be willing to pay for if I was to create and/or support, in the async/falcon eco-system?

**Comment by artrybalko** [comment]
That's a good question. I'll be happy to advocate for a higher sponsorship tier as we expand our usage of async. I'm not sure I can think of anything off the top of my head that would make sense for a commercial license at the current level of usage. Perhaps something around the database and activerecord layer? We haven't explored that at all yet since optimizing external requests has bigger returns.

**Pull request closed without merging**
